name: preview_xml_changes
# label used for menu selection
label: Preview XML Changes

description: |
  Find and highlight differences between two configs

type: workflow

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  order: 2
  collection:
    - Skillet Builder

variables:
  - name: skillet_source
    description: Source of Changes
    type_hint: dropdown
    default: "online"
    help_text: |
      Select from where you would like to compare changes. Either from a device or from a set of
      uploaded configurations.
    dd_list:
      - key: "From Running NGFW"
        value: "online"
      - key: "From uploaded Configs"
        value: "offline"

snippets:
  - name: generate_skillet_preview_offline
    when: skillet_source == "offline"
  - name: generate_skillet_preview_online
    when: skillet_source == "online"
  - name: generate_skillet_preview_output
