name: generate_set_cli
label: Generate Set CLI Commands

description: |
  Creates a list of CLI Set commands from the difference between two XML config files.

type: workflow

labels:
  order: 5
  collection:
    - Skillet Builder

variables:
  - name: skillet_source
    description: Source of Changes
    type_hint: dropdown
    default: "online"
    help_text: |
      Select from where you would like to compare changes. Either from a device or from a set of
      uploaded configurations.
    dd_list:
      - key: "From Running NGFW"
        value: "online"
      - key: "From uploaded Configs"
        value: "offline"

snippets:
  - name: generate_set_cli_offline
    when: skillet_source == "offline"
  - name: generate_set_cli_online
    when: skillet_source == "online"
