name: generate_skillet_snippets_from_config
label: Generate Skillet Snippets From Uploaded Configs

description: |
  Creates a list of XML snippets that have been added or modifed between a two XML configuration files.

type: python3

labels:
  order: 4
  collection:
    - Skillet Builder

variables:
  - name: configs
    description: Encoded Configs
    default:
    type_hint: text_area
    attributes:
      rows: 5
      cols: 10

snippets:
  - name: script
    file: generate_skillet_snippets_from_configs.py
    input_type: env
    output_type: json
    outputs:
      - name: snippets

