# part of the panhandler application with docs at
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst

# unique snippet name
name: generate_skillet_preview_from_config_template
# label used for menu selection
label: XML Modifications Template
description: |
  Display the results of the Preview XML Changes Skillet

type: template

labels:
  order: 5
  collection:
   - Kitchen Sink

variables:

snippets:
  - name: preview_xml_output
    file: output.j2
    template_title: XML Modifications
