name: Generate_Skillet_from_configs_workflow
label: Generate a Skillet From Configs Workflow

description: |
  Use a two XML configurations to generate a Skillet from scratch

type: workflow

labels:
  order: 2
  collection:
    - Skillet Builder

variables:

snippets:
  - name: generate_skillet_snippets_from_config
  - name: skeleton_yaml_file_xml