name: generate_skillet_snippets_from_config
label: Generate Skillet Snippets From Uploaded Configs

description: |
  Creates a list of XML snippets that have been added or modifed between a two XML configuration files.

type: python3

labels:
  collection:
   - Kitchen Sink

variables:
  - name: skillet_source
    type_hint: hidden
    default: offline
  - name: BASE_CONFIG
    description: Base Configuration
    default:
    type_hint: file
    help_text: Initial XML configuration from Before any changes are made
  - name: LATEST_CONFIG
    description: Modified Configuration
    default:
    type_hint: file
    help_text: XML configuration from After any changes are made

snippets:
  - name: script
    file: ../../generate_skillet_snippets_from_configs.py
    input_type: env
    output_type: json
    outputs:
      - name: snippets

