name: configuration_explorer
label: Configuration Explorer Tool

description: |
  Allows you to test XPATH queries and see the results both as XML and JSON. This is useful to help build skillets
  quickly.

type: python3

labels:
  order: 7
  collection:
    - Skillet Builder

variables:
  - name: source
    description: Configuration Mode
    type_hint: dropdown
    dd_list:
      - key: "Online"
        value: "online"
      - key: "Offline"
        value: "offline"
    help_text: Online will query a PAN-OS device via API, Offline will allow you to paste in a full Configuration.

  - name: TARGET_IP
    description: Hostname
    default: 10.10.10.10
    type_hint: fqdn_or_ip
    toggle_hint: 
      source: source
      value: online
  - name: TARGET_USER
    description: Username
    default: admin
    type_hint: text
    toggle_hint:
      source: source
      value: online
  - name: TARGET_PASSWORD
    description: Password
    default:
    type_hint: password
    toggle_hint:
      source: source
      value: online

  - name: config_source
    description: Online Configuration Source
    type_hint: dropdown
    dd_list:
      - key: "Running Configuration"
        value: "running"
      - key: "Candidate Configuration"
        value: "candidate"
    toggle_hint:
      source: source
      value: online
    help_text: Perform XPATH query against running or candidate configuration

  - name: xpath
    description: XPATH Query
    default: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles
    type_hint: text
    help_text: XPath Query to run against the configuration.

  - name: config
    description: Offline Config
    type_hint: text_area
    default:
    attributes:
      rows: 40
      cols: 40
    toggle_hint:
      source: source
      value: offline
    help_text: Paste in a full PAN-OS Configuration here for offline mode.


snippets:
  - name: script
    file: ../configuration_explorer.py
    input_type: env

