name: generate_skillet_preview_from_config
label: Preview XML Changes between configs

description: |
  Find and highlight differences between two configs

type: python3

labels:
  order: 4
  collection:
    - Skillet Builder

variables:
  - name: BASE_CONFIG
    description: Base Configuration
    default:
    type_hint: file
    help_text: Initial XML configuration from Before any changes are made
  - name: LATEST_CONFIG
    description: Modified Configuration
    default:
    type_hint: file
    help_text: XML configuration from After any changes are made

snippets:
  - name: script
    file: generate_skillet_preview_from_configs.py
    input_type: env


