name: generate_skillet_preview_offline
label: Preview XML Changes between Configs

description: |
  Find and highlight differences between two configs

type: python3

labels:
  collection:
   - Kitchen Sink

variables:
  - name: BASE_CONFIG
    description: Base Configuration
    default:
    type_hint: file
    help_text: Initial XML configuration from Before any changes are made
  - name: LATEST_CONFIG
    description: Modified Configuration
    default:
    type_hint: file
    help_text: XML configuration from After any changes are made

snippets:
  - name: script
    file: ../../generate_skillet_preview.py
    input_type: env
    output_type: text
    outputs:
      - name: skillet_preview

