name: generate_set_cli_online
label: Generate set commands from device

description: |
  Creates a list of CLI Set commands from the difference between two XML config files.

type: python3

labels:
  collection:
   - Kitchen Sink

variables:
  - name: skillet_source
    type_hint: hidden
    default: online
  - name: TARGET_IP
    description: Hostname
    default: 10.10.10.10
    type_hint: fqdn_or_ip
  - name: TARGET_USER
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default:
    type_hint: password
  - name: CONFIG_SOURCE
    description: Configuration Source
    type_hint: dropdown
    default: "False"
    dd_list:
      - key: "From Previously Committed Running Configuration"
        value: previous
      - key: "From Candidate Configuration"
        value: candiate
      - key: "From Specific Configuration Version"
        value: specific
    help_text: |
      Choose a configuration source to use to generate a list of changes. Previously committed will generate all
      changes made between the last commit and the current running configuration. Candidate will generate all changes
      between the running configuration and the current candidate configuration. Specific Configuration Version will
      use the differences between the current running configuration and a versioned backup of the running config.
  - name: CONFIG_VERSION
    description: Previous Configuration Version Number
    default: -1
    type_hint: text
    toggle_hint:
      source: CONFIG_SOURCE
      value: specific
    help_text: |
      Use a specific configuration version number, as found from 'show config audit info'. You may also use negative
      numbers to indicate the most to least recent running configuration versions.


snippets:
  - name: script
    file: ../../generate_set_cli.py
    input_type: env

