name: get_and_compress_configs
label: Upload Configs for Skillet Generation

description: |
  Upload your Base and Latest configs

type: template

labels:
  order: 4
  collection:
    - Skillet Builder

variables:
  - name: BASE_CONFIG
    description: Base Configuration
    default: <xml><help>Paste your base config here</help></xml>
    type_hint: text_area
    attributes:
      rows: 5
      cols: 10
  - name: LATEST_CONFIG
    description: Modified Configuration
    default: <xml><help>Paste your modified config here</help></xml>
    type_hint: text_area
    attributes:
      rows: 5
      cols: 10

snippets:
  - name: config_data.j2
    file: config_data.j2
    output_type: text
    outputs:
      - name: configs

